sudo : required
dist : trusty
cache : 
  - apt
branches : 
  only : 
    - master
    - dev
env:
  global:
    - HOME=/home/travis
before_install :
  - sudo apt-get update -qq
script :
  - bash -eux -c "$(curl -SsfL https://git.io/ubuntu-tmux-install)"
  - $HOME/usr/local/bin/tmux -V

